ProjectTrackerApplicationLayer/Controllers/ActivityController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using ProjectTrackerBusinessLayer.Repositories.ProjectRelatedRepositories;
using System.Data;
using System.Security.Claims;

namespace ProjectTrackerApplicationLayer.Controllers
{
    [Authorize(Roles= "Admin,Team Manager")]
    public class ActivityController : Controller
    {
        private readonly IActivityRepository activityRepo;
        public ActivityController(IActivityRepository activityRepo)
        {
            this.activityRepo = activityRepo;
        }

        public IActionResult ProjectActivities()
        {
            var userID = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var projectActivities =activityRepo.GetProjectActivities(userID);
            return View(projectActivities);
        }
        public IActionResult SprintActivities()
        {
            var userID = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var sprintActivities = activityRepo.GetSprintActivities(userID);
            return View(sprintActivities);
        }
        public IActionResult MissionActivities()
        {
            var userID = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var missionActivities = activityRepo.GetMissionActivities(userID);
            return View(missionActivities);
        }
        public IActionResult WorkActivities()
        {
            var userID = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var workActivities = activityRepo.GetWorkActivities(userID);
            return View(workActivities);
        }
    }
}

ProjectTrackerApplicationLayer/Controllers/ProjectController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProjectTrackerApplicationLayer.DTO;
using ProjectTrackerBusinessLayer.Entities;
using ProjectTrackerBusinessLayer.Repositories.ProjectRelatedRepositories;
using ProjectTrackerBusinessLayer.Repositories.UsersRepositories;
using System;
using System.Security.Claims;

namespace ProjectTrackerApplicationLayer.Controllers
{
    [Authorize]

    public class ProjectController : Controller
    {
        private readonly ITeamLeaderRepository teamLeaderRepo;
        private readonly ITeamMemberRepository teamMemberRepo;
        private readonly IProjectRepository projectRepo;
        private readonly IStatusesRepository statusesRepo;
        private readonly IActivityRepository activityRepo;
        public ProjectController(IProjectRepository projectRepo, ITeamLeaderRepository teamLeaderRepo, ITeamMemberRepository teamMemberRepo, IStatusesRepository statusesRepo, IActivityRepository activityRepo)
        {
            this.projectRepo = projectRepo;
            this.teamLeaderRepo = teamLeaderRepo;
            this.teamMemberRepo = teamMemberRepo;
            this.statusesRepo = statusesRepo;
            this.activityRepo = activityRepo;
        }
        //New Project Form
        [Authorize(Roles ="Team Manager,Admin")]
        public IActionResult CreateProject()
        {
            ViewBag.Leaders = teamLeaderRepo.GetAllTeamLeaders();
            ViewBag.Members = teamMemberRepo.AllTeamMembers();
            return View();

        }

        //Adding New Project toDataBase
        [Authorize(Roles = "Team Manager,Admin")]
        public IActionResult AddingProject(ProjectDTO projectDTO)
        {
            if (ModelState.IsValid)
            {
                var project = new Project()
                {
                    Name = projectDTO.Name,
                    Description = projectDTO.Description,
                    DeadLine = projectDTO.DeadLine,
                    StatusID = 1,
                };
                int deadLine = project.DeadLine.CompareTo(DateTime.Now); //check
                if(deadLine < 1)
                {
                    ModelState.AddModelError(String.Empty, "Deadline can't be before today's date");
                    ViewBag.Leaders = teamLeaderRepo.GetAllTeamLeaders();
                    ViewBag.Members = teamMemberRepo.AllTeamMembers();
                    return View("CreateProject", projectDTO);
                }
                projectRepo.AddNewProject(project);
                var ManagerID = User.FindFirstValue(ClaimTypes.NameIdentifier);
                projectRepo.ProjectUsers(project.ProjectID, projectDTO.TeamMembersIDs, projectDTO.TeamLeaderID, ManagerID);
                activityRepo.ProjectActivity(project);
                return RedirectToAction("ManagerProjects", new { managerID = ManagerID });
            }
            else
            {
                ViewBag.Leaders = teamLeaderRepo.GetAllTeamLeaders();
                ViewBag.Members = teamMemberRepo.AllTeamMembers();
                return View("CreateProject", projectDTO);
            }
        }

        //All projects for logged Manager
        [Authorize(Roles = "Team Manager,Admin")]
        public IActionResult ManagerProjects()
        {
            var managerID = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var Projects = projectRepo.GetProjectForUser(managerID);
            return View(Projects);
        }

        //Edit Project form
        [Authorize(Roles = "Team Manager,Admin")]
        public IActionResult EditProject(int ProjectID)
        {
            ViewBag.Leaders = teamLeaderRepo.GetAllTeamLeaders();
            ViewBag.Members = teamMemberRepo.AllTeamMembers();
            ViewBag.Statuses = statusesRepo.Statuses();
            return View(projectRepo.GetProject(ProjectID));
        }

        //Submitting editting to database
        [Authorize(Roles = "Team Manager,Admin")]
        public IActionResult EdittingProject(ProjectDTO projectDTO)
        {
            if (ModelState.IsValid)
            {
                var project = new Project()
                {
                    ProjectID = projectDTO.ProjectID,
                    Name = projectDTO.Name,
                    Description = projectDTO.Description,
                    DeadLine = projectDTO.DeadLine,
                    StatusID = projectDTO.StatusID,
                };
                var ManagerID = User.FindFirstValue(ClaimTypes.NameIdentifier);

                projectRepo.EdittingProject(project, projectDTO.TeamMembersIDs, projectDTO.TeamLeaderID, ManagerID);
                activityRepo.ProjectActivity(project);
                return RedirectToAction("ManagerProjects", new { managerID = ManagerID });
            }
            else
            {
                ViewBag.Leaders = teamLeaderRepo.GetAllTeamLeaders();
                ViewBag.Members = teamMemberRepo.AllTeamMembers();
                return View(" EditProject", projectDTO);
            }

        }

        //List of projects assigned for logged TL
        [Authorize(Roles ="Team Leader,Admin")]
        public IActionResult LeadersProjects()
        {
            var teamLeaderID = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return View(projectRepo.GetProjectForUser(teamLeaderID));
        }

        //List of Projects assigned for logged member
        [Authorize(Roles ="Team Member,Admin")]
        public IActionResult MembersProjects()
        {
            var memberID = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var projects = projectRepo.GetProjectForUser(memberID);
            return View(projects);
        }

    }
}

ProjectTrackerApplicationLayer/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ProjectTrackerApplicationLayer.DTO;
using ProjectTrackerBusinessLayer.Entities;
using ProjectTrackerBusinessLayer.Repositories.RolesRepositories;
using ProjectTrackerBusinessLayer.Repositories.UsersRepositories;
using System;
using System.Collections.Generic;
using System.Linq;

namespace ProjectTrackerApplicationLayer.Controllers
{
    [Authorize]

    public class UserController : Controller
    {
        //private readonly IRoleRepository roleRepository;
        private readonly IPositionRepository positionRepository;
        
        public UserController(/*IRoleRepository roleRepository, */IPositionRepository positionRepository)
        {
            //this.roleRepository = roleRepository;
            this.positionRepository = positionRepository;
           

        }
        [Authorize(Roles ="Admin")]
        public IActionResult NewEmployeeForm()
        {
            //ViewBag.Roles = roleRepository.AllRoles(); //still have to figure out if roles are needed, right now its useless
            //it is not needed
            var pos = positionRepository.AllPositions();
            pos.Remove(pos.SingleOrDefault(x => x.PositionID == 5));
            ViewBag.Positions = pos;
            return View();
        }
        [Authorize(Roles = "Admin")]
        public IActionResult AddingNewEmployee(List<string> RoleIDs, int PositionID)
        {
            return PositionID switch
            {
                1 => RedirectToAction("NewTeamManagerForm", "TeamManager"),//can send the list of roles by using anon obj (new { RoleIDs= RoleIDs})
                2 => RedirectToAction("NewTeamLeaderForm", "TeamLeader"),
                3 => RedirectToAction("NewTeamMemberForm", "TeamMember", new { rank = PositionID }),
                4 => RedirectToAction("NewTeamMemberForm", "TeamMember", new { rank = PositionID }),
                _ => View(),
            };
        }
        
    }
}

ProjectTrackerApplicationLayer/Views/Shared/_FileInputLayout.cshtml
@using Microsoft.AspNetCore.Identity
@using ProjectTrackerBusinessLayer.Entities
@inject SignInManager<User> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>

	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="">
	<meta name="author" content="">

	<title>Project Tracker</title>
	<link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
		  rel="stylesheet">

	<link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
	<script href="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js" type="text/javascript"></script>
	<link href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" rel="stylesheet" />
	<link href="/Theme2/css/sb-admin-2.min.css" rel="stylesheet">
	<link href="/Theme2/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet" />
	<script src="https://kit.fontawesome.com/fc910579a5.js" crossorigin="anonymous"></script>

	<link rel="stylesheet" href="~/lib/bootstrap4/dist/css/bootstrap.min.css" />


	<link rel="stylesheet" href="~/css/site.css" />
	<link href="/select2/css/select2.min.css" rel="stylesheet" />

	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" crossorigin="anonymous">

	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.min.css" crossorigin="anonymous">



	<link href="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-fileinput@5.5.0/css/fileinput.min.css" media="all" rel="stylesheet" type="text/css" />


	<script src="https://code.jquery.com/jquery-3.6.0.min.js" crossorigin="anonymous"></script>


	<script src="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-fileinput@5.5.0/js/plugins/buffer.min.js" type="text/javascript"></script>
	<script src="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-fileinput@5.5.0/js/plugins/filetype.min.js" type="text/javascript"></script>


	<script src="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-fileinput@5.5.0/js/plugins/piexif.min.js" type="text/javascript"></script>


	<script src="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-fileinput@5.5.0/js/plugins/sortable.min.js" type="text/javascript"></script>


	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>

	<script src="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-fileinput@5.5.0/js/fileinput.min.js"></script>

	@* scripts *@



</head>

<body id="page-top" style="margin-bottom:-10px">

	<!-- Page Wrapper -->
	<div id="wrapper">
		@if (SignInManager.IsSignedIn(User))
		{
			<!-- Sidebar -->
			<ul class="navbar-nav bg-gradient-info sidebar sidebar-dark accordion" id="accordionSidebar">

				<!-- Sidebar - Brand -->
				<a class="sidebar-brand d-flex align-items-center justify-content-center text-white">
					<div class="sidebar-brand-icon rotate-n-15">
						<i class="fa-solid fa-laptop-code"></i>
					</div>
					<div class="sidebar-brand-text mx-3">Project Tracker</div>
				</a>

				<!-- Divider -->
				<br />
				<hr class="text-white sidebar-divider my-0">
				<!--Team Manager side bar content-->
				@if (User.IsInRole("Team Manager"))
				{
					<!-- Nav Item - Dashboard -->
					<li class="nav-item" data-href="/DashBoard/ManagerDashBoard">
						<a class="nav-link" href="/DashBoard/ManagerDashBoard">
							<i class="fas fa-fw fa-tachometer-alt"></i>
							<span>Dashboard</span>
						</a>
					</li>
					<!-- Divider -->
					<hr class="text-white sidebar-divider">
					<!-- Heading -->
					<div class="sidebar-heading">
						<i class="fas fa-folder"></i>
						<span>Activities</span>
					</div>
					<!-- Nav Items -->
					<li class="nav-item" data-href="/Activity/ProjectActivities">
						<a class="nav-link" href="/Activity/ProjectActivities">
							<span>Project Activities</span>
						</a>
					</li>
					<li class="nav-item" data-href="/Activity/SprintActivities">
						<a class="nav-link" href="/Activity/SprintActivities">
							<span>Sprint Activities</span>
						</a>
					</li>
					<li class="nav-item" data-href="/Activity/MissionActivities">
						<a class="nav-link" href="/Activity/MissionActivities">
							<span>Mission Activities</span>
						</a>
					</li>
					<li class="nav-item" data-href="/Activity/WorkActivities">
						<a class="nav-link" href="/Activity/WorkActivities">
							<span>Work Activities</span>
						</a>
					</li>
					<!-- Divider -->
					<hr class="text-white sidebar-divider">
					<!-- Heading -->
					<div class="sidebar-heading">
						<i class="fas fa-archive"></i>
						<span>Project Management</span>
					</div>
					<!-- Nav Items -->
					<li class="nav-item" data-href="/Project/CreateProject">
						<a class="nav-link" href="/Project/CreateProject">

							<span>Create Project</span>
						</a>
					</li>
					<li class="nav-item" data-href="/Project/ManagerProjects">
						<a class="nav-link" href="/Project/ManagerProjects">
							<span>My Projects</span>
						</a>
					</li>
				}
				<!--Admin side bar content-->
				@if (User.IsInRole("Admin"))
				{
					<!-- Nav Item - Dashboard for Admin -->
					<li class="nav-item" data-href="/DashBoard/AdminDashBoard">
						<a class="nav-link" href="/DashBoard/AdminDashBoard">
							<i class="fas fa-fw fa-tachometer-alt"></i>
							<span>Dashboard</span>
						</a>
					</li>
					<!-- Divider -->
					<hr class="text-white sidebar-divider">
					<!-- Heading -->
					<div class="sidebar-heading">
						<i class="fa fa-solid fa-users"></i>
						<span>Employees</span>
					</div>
					<!-- Nav Items -->
					<li class="nav-item" data-href="/TeamManager/AllTeamManagers">
						<a class="nav-link" href="/TeamManager/AllTeamManagers">
							<span>Team Managers</span>
						</a>
					</li>
					<li class="nav-item" data-href="/TeamLeader/AllTeamLeaders">
						<a class="nav-link" href="/TeamLeader/AllTeamLeaders">
							<span>Team Leaders</span>
						</a>
					</li>
					<li class="nav-item" data-href="/TeamMember/AllTeamMember">
						<a class="nav-link" href="/TeamMember/AllTeamMembers">
							<span>Team Members</span>
						</a>
					</li>
					<!-- Divider -->
					<hr class="text-white sidebar-divider">
					<!-- Heading -->
					<li class="nav-item">
						<a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
							<i class="fa-solid fa-user-plus"></i>
							<span>Add new Employee</span>
						</a>
						<div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
							<div class="bg-white py-2 collapse-inner rounded">
								<h6 class="collapse-header">New Employee position:</h6>
								<a class="collapse-item" href="/User/AddingNewEmployee?PositionID=1">Team Manager</a>
								<a class="collapse-item" href="/User/AddingNewEmployee?PositionID=2">Team Leader</a>
								<a class="collapse-item" href="/User/AddingNewEmployee?PositionID=3">Team Member Senior</a>
								<a class="collapse-item" href="/User/AddingNewEmployee?PositionID=4">Team Member Junior</a>
							</div>
						</div>
					</li>
				}
				<!--Team Leader side bar content-->
				@if (User.IsInRole("Team Leader"))
				{
					<!-- Nav Item - Dashboard -->
					<li class="nav-item" data-href="/DashBoard/LeaderDashBoard">
						<a class="nav-link" href="/DashBoard/LeaderDashBoard">
							<i class="fas fa-fw fa-tachometer-alt"></i>
							<span>Dashboard</span>
						</a>
					</li>
					<!-- Divider -->
					<hr class="text-white sidebar-divider">

					<!-- Nav Items -->
					<li class="nav-item" data-href="/Project/LeadersProjects">
						<a class="nav-link" href="/Project/LeadersProjects">
							<i class="fa-solid  fa-folder-tree"></i>
							<span>My Projects</span>
						</a>
					</li>
				}
				@if (User.IsInRole("Team Member"))
				{
					<!-- Nav Item - Dashboard -->
					<li class="nav-item" data-href="/DashBoard/MemberDashBoard">
						<a class="nav-link" href="/DashBoard/MemberDashBoard">
							<i class="fas fa-fw fa-tachometer-alt"></i>
							<span>Dashboard</span>
						</a>
					</li>
					<!-- Divider -->
					<hr class="text-white sidebar-divider">

					<!-- Nav Items -->
					<li class="nav-item" data-href="/Project/MembersProjects">
						<a class="nav-link" href="/Project/MembersProjects">
							<i class="fa-solid  fa-folder-tree"></i>
							<span>My Projects</span>
						</a>
					</li>
				}

				<!-- Divider -->
				<hr class="sidebar-divider text-white d-none d-md-block">

				<!-- Sidebar Toggler (Sidebar) -->
				<div class="text-center d-none d-md-inline">
					<button class="rounded-circle border-0" id="sidebarToggle">
					</button>
				</div>
			</ul>
		}
		<!-- End of Sidebar -->
		<!-- Content Wrapper -->
		<div id="content-wrapper" class="d-flex flex-column">

			<!-- Main Content -->
			<div id="content">

				<!-- Topbar -->
				<nav class="navbar navbar-expand navbar-light bg-white topbar static-top shadow">

					<!-- Sidebar Toggle (Topbar) -->
					<button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
						<i class="fa fa-bars"></i>
					</button>



					<!-- Topbar Navbar -->
					<ul class="navbar-nav ml-auto">
						<div class="topbar-divider d-none d-sm-block"></div>
						@if (User.Identity.IsAuthenticated)
						{
							<!-- Nav Item - User Information -->
							<li class="nav-item dropdown no-arrow">
								<a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
							   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									<i class="fas fa-user fa-fw"></i> <span class="mr-2 d-none d-lg-inline text-gray-600 small"> &nbsp;  @User.Identity.Name</span>
								</a>

								<!-- Dropdown - User Information -->
								<div class="dropdown-menu dropdown-menu-right "
								 aria-labelledby="userDropdown">
									<a class="dropdown-item" data-toggle="modal" data-target="#logoutModal">
										<i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
										<span>Logout</span>
									</a>
								</div>

							</li>
						}
						else
						{
							<li class="nav-item">
								<a class="nav-link">
									No User
								</a>
							</li>
						}
					</ul>

				</nav>
				<!-- End of Topbar -->
				<!-- Begin Page Content -->
				<div class="container-fluid mt-5">
					<main id="Body" role="main" class="pb-3">
						@RenderBody()
					</main>
				</div>
				<!-- End of Main Content -->
				<!-- Footer -->
				@*           <footer>
				Empty
				</footer>*@
				<!-- End of Footer -->

			</div>
		</div>
		<!-- Scroll to Top Button-->
		<a class="scroll-to-top rounded" href="#page-top">
			<i class="fas fa-angle-up"></i>
		</a>

		<!-- Logout Modal-->
		<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
			 aria-hidden="true">
			<div class="modal-dialog" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
						<button class="close" type="button" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">×</span>
						</button>
					</div>
					<div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
					<div class="modal-footer">
						<button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
						<form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
							<button type="submit" class="btn btn-info">Logout</button>
						</form>
					</div>
				</div>
			</div>
		</div>

		<script src="/Theme2/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
		<script src="/Theme2/vendor/jquery-easing/jquery.easing.min.js"></script>
		<script src="/Theme2/js/sb-admin-2.min.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
		<script src="/Theme2/vendor/chart.js/Chart.min.js"></script>
		<script src="~/lib/bootstrap4/dist/js/bootstrap.bundle.min.js"></script>
		<script src="~/js/site.js" asp-append-version="true"></script>

		<script src="/select2/js/select2.min.js"></script>
		<script src="/Theme2/vendor/datatables/jquery.dataTables.min.js"></script>
		<script src="/Theme2/vendor/datatables/dataTables.bootstrap4.min.js"></script>

		<script>
			$(document).ready(function () {
				const elems = document.getElementsByClassName('nav-item');
				for (var i = 0; i < elems.length; i++) {
					const elem = elems[i];
					const href = elem.dataset ? elem.dataset.href : undefined;
					if (href != undefined && window.location.href.includes(href)) {
						elem.classList.add('active');
					}
				}
			});
		</script>
</body>

</html>

ProjectTrackerApplicationLayer/Views/Shared/_LayoutMain.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] ProjectTracker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="/select2/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="/select2/js/select2.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</head>
@using ProjectTrackerBusinessLayer.Entities;
@using ProjectTrackerBusinessLayer.Data;
@using Microsoft.AspNetCore.Identity;
@using System.Security.Claims;
@inject ApplicationDbContext _context;
@inject SignInManager<User> SignManager;
<body>
    <header>
        @{
            if (_context.Users.Count() != 0)
            {
                <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                    <a class="navbar-brand"  asp-area="" asp-controller="Home" asp-action="Index">ProjectTracker</a>
                    <div class="container">
                        
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                            <partial name="_LoginPartial" />
                            <ul class="navbar-nav flex-grow-1 justify-content-center">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                </li>
                                @if (User.IsInRole("Team Manager"))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Project" asp-action="CreateProject">Create Project</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-are="" asp-controller="Project" asp-action="ManagerProjects" asp-route-managerID="@User.FindFirstValue(ClaimTypes.NameIdentifier)">Projects</a>
                                    </li>
                                }
                                @if (User.IsInRole("Team Leader"))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Project" asp-route-teamLeaderID="@User.FindFirstValue(ClaimTypes.NameIdentifier)" asp-action="LeadersProjects">My Projects</a>
                                    </li>
                                }
                                @if (User.IsInRole("Team Member"))
                                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Project" asp-route-memberID="@User.FindFirstValue(ClaimTypes.NameIdentifier)" asp-action="MembersProjects">My Projects</a>
                                    </li>
                                }
                                @if (User.IsInRole("Admin")) 
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="NewEmployeeForm">Add Employee</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="TeamManager" asp-action="AllTeamManagers">Team Managers</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="TeamLeader" asp-action="AllTeamLeaders">Team Leaders</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="TeamMember" asp-action="AllTeamMembers">Team Members</a>
                                    </li>
                                    <li class="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle text-dark"  id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            Activities
                                        </a>
                                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                            <a class="dropdown-item" asp-controller="Activity" asp-action="ProjectActivities">Project Activities</a>
                                            <div class="dropdown-divider"></div>
                                            <a class="dropdown-item" asp-controller="Activity" asp-action="SprintActivities">Sprint Activities</a>
                                            <div class="dropdown-divider"></div>
                                            <a class="dropdown-item" asp-controller="Activity" asp-action="MissionActivities">Mission Activities</a>
                                            <div class="dropdown-divider"></div>
                                            <a class="dropdown-item" asp-controller="Activity" asp-action="WorkActivities">Work Activities</a>
                                        </div>
                                    </li>
                                }
                            </ul>
                      </div>
                     </div>
                </nav>
            }
        }
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ProjectTrackerApplicationLayer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    @RenderSection("Scripts", required: false)
</body>
</html>