ProjectTrackerApplicationLayer/Controllers/WorkController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ProjectTrackerBusinessLayer.Entities;
using ProjectTrackerBusinessLayer.Repositories.ProjectRelatedRepositories;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Security.Cryptography.X509Certificates;

namespace ProjectTrackerApplicationLayer.Controllers
{
    [Authorize]

    public class WorkController : Controller
    {
        private readonly IWorkRepository workRepo;
        private readonly IMissionRepository missionRepo;
        private readonly IAttachmentRepository attachmentRepo;
        private readonly IStatusesRepository statusesRepo;
        private readonly IActivityRepository activityRepo;
        
        public WorkController(IWorkRepository workRepo, IMissionRepository missionRepo, IAttachmentRepository attachmentRepo, IStatusesRepository statusesRepo, IActivityRepository activityRepo)
        {
            this.workRepo = workRepo;
            this.missionRepo = missionRepo;
            this.attachmentRepo = attachmentRepo;
            this.statusesRepo = statusesRepo;
            this.activityRepo = activityRepo;
        }

        //team manager view for works
        [Authorize(Roles = "Team Manager,Admin")]
        public IActionResult AllWorksManager(int missionID)
        {
            var works = workRepo.MissionsWorks(missionID);
            ViewBag.mission = missionRepo.GetMission(missionID);
            return View(works);
        }

        //team leader view for works
        [Authorize(Roles ="Team Leader,Admin")]
        public IActionResult AllWorksLeader(int missionID)
        {
            var works = workRepo.MissionsWorks(missionID);
            ViewBag.Mission = missionRepo.GetMission(missionID);

            return View(works);
        }

        //team member view for works
        [Authorize(Roles ="Team Member,Admin")]
        public IActionResult MembersWorks(int missionID)
        {
            
            string memberID = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var works = workRepo.MembersWorks(missionID, memberID);
            ViewBag.Mission = missionRepo.GetMission(missionID);
            ViewBag.StatusesChecker = missionRepo.MissionStatusChecker(missionID); 
            ViewBag.missionID = missionID;

            return View(works);
        }

        //add work form
        [Authorize(Roles = "Team Member,Admin")]
        public IActionResult AddWork(int missionID)
        {
            ViewBag.mission = missionRepo.GetMission(missionID);
            return View();
        }

        //Adding work to database
        [Authorize(Roles = "Team Member,Admin")]
        [HttpPost]
        public IActionResult AddingWork(List<IFormFile> files, Work work, string memberID)
         {
            ModelState.Remove("Files");
            if (ModelState.IsValid)
            {
                work.StatusID = 1;

                var workID = workRepo.AddWork(work);

                attachmentRepo.AddWorksAttachments(files, workID);

                activityRepo.WorkActivity(work);
                return RedirectToAction("MembersWorks", new { work.MissionID, memberID });

            }
            else
            {
                ViewBag.mission = missionRepo.GetMission(work.MissionID);
                return View("AddWork",  work );
            }

        }

        //Edit work form
        [Authorize(Roles = "Team Member,Admin")]
        public IActionResult EditWork(int workID, int missionID)
        {
            var work = workRepo.GetWork(workID);
            ViewBag.mission = missionRepo.GetMission(missionID);
            ViewBag.Attachments = attachmentRepo.GetAttachments(workID);
            ViewBag.Statuses = statusesRepo.Statuses();
            return View(work);
        }

        //Editting work in database
        [Authorize(Roles = "Team Member,Admin")]
        public IActionResult EdittingWork(List<int> AttachmentIDs, Work workEditted, List<IFormFile> files, string memberID)
        {
            if (ModelState.IsValid)
            {
                attachmentRepo.DeleteAttachments(AttachmentIDs, workEditted.WorkID);
                workRepo.UpdateWork(workEditted);
                attachmentRepo.AddWorksAttachments(files, workEditted.WorkID);
                activityRepo.WorkActivity(workEditted);
                return RedirectToAction(nameof(MembersWorks), new { workEditted.MissionID, memberID });
            }
            else
            {
                ViewBag.Attachments = attachmentRepo.GetAttachments(workEditted.WorkID);
                ViewBag.Statuses = statusesRepo.Statuses();
                return View("EditWork", workEditted);
            }
        }

        //Team Leader's note on work
        [Authorize(Roles ="Team Leader,Admin")]
        public IActionResult AddRejectNote(string note, int workID)
        {
            var work = workRepo.GetWork(workID);
            work.TeamLeaderNote = note;
            work.StatusID = 3;
            workRepo.UpdateWork(work);
            activityRepo.WorkActivity(work);
            return RedirectToAction("AllWorksLeader", new { work.MissionID });
        }

        //Team Leader approve work
        [Authorize(Roles ="Team Leader,Admin")]
        public IActionResult LeaderApprove(int workID)
        {
            var workApproved = workRepo.GetWork(workID);
            workApproved.StatusID = 2;
            workApproved.TeamLeaderNote = " ";
            workRepo.UpdateWork(workApproved);
            activityRepo.WorkActivity(workApproved);
            return RedirectToAction("AllWorksLeader", new { workApproved.MissionID });
        }
    }
}

ProjectTrackerApplicationLayer/Views/Work/AddWork.cshtml
@using ProjectTrackerBusinessLayer.Entities;

@model Work
@{
    Layout = "~/Views/Shared/_FileInputLayout.cshtml";

    ViewData["Title"] = "Submit Work";
}

<br />
<h2 class="text-center">New Work Form</h2>
<br />
<hr />
<h4 class="text-center">@ViewBag.Mission.Name</h4>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-8">
            <form id="uploadform" asp-action="AddingWork" method="post" enctype="multipart/form-data">
                <div asp-validation-summary="All" class="text-danger"></div>
                <input value="@ViewBag.mission.MissionID" name="missionID" hidden />
                <input value="@ViewBag.mission.TeamMemberID" name="memberID" hidden />
                <input value="1" name="StatusID" hidden />
                <div class="form-group">
                    <label asp-for="Name" class="label-control"></label>
                    <input asp-for="Name" class="form-control col-md-5" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="WorkDescription" class="label-control"></label>
                    <textarea asp-for="WorkDescription" class="form-control"></textarea>
                    <span asp-validation-for="WorkDescription" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label class="label-control">Attachments</label> <br />
                    <input type="file" class="file" multiple id="FileLib" name="files" />
                    <script>
                        // with plugin options
                        $("#FileLib").fileinput({ 'showUpload': false, 'previewFileType': 'any' });
                    </script>
                </div>
                <br />
                <input type="submit" value="Add" class="btn btn-outline-info" />
            </form>
        </div>
    </div>
</div>

ProjectTrackerApplicationLayer/Views/Work/AllWorksLeader.cshtml
@using ProjectTrackerBusinessLayer.Entities;
@using System.Linq;
@using System.Collections.Generic;
@model List<Work>;
@*@{
    Layout = "~/Views/Shared/_LayoutFluidContainer.cshtml";
}*@

<h1 class="text-center">Mission: @ViewBag.Mission.Name <br /> Works</h1>

<br />

<h5 class="text-danger font-weight-bolder mx-3">Last date to submit work:@ViewBag.Mission.Sprint.EndDate </h5>

<hr />
<div class="row mx-3">

	@{
		var workApproved = @Model.Where(x => x.StatusID == 2).ToList().Count;
		var workCount = Model.Count();
		if (workApproved == workCount)
		{
			<a class="btn bg-gradient-info text-white" href="/Mission/AllWorkApproved?missionID=@ViewBag.Mission.MissionID">Done</a>
		}
		else
		{
			<a class="btn disabled bg-info text-white">Done</a>

		}

	}
</div>
<br />


<div class="row justify-content-center">
	<div class=" col-12">
		<div class="card shadow mx-3 mb-4">

			<div class="card-body">
				<div class="table-responsive">
					<table class="table table-bordered table-hover cell-border" id="WorkTable" width="100%" cellspacing="0">
						<thead>
							<tr class="font-weight-bolder">
								<th>
									Work Title
								</th>
								<th>
									Work Description
								</th>
								<th>
									Team Member
								</th>
								<th>
									Status
								</th>
								<th>
									Attachment Submitted
								</th>
								<th>
									Team Leader note
								</th>
								<th>
									Action
								</th>
							</tr>
						</thead>
						<tbody>
							@{
								foreach (var work in Model)
								{
									<tr>
										<td> @work.Name</td>
										<td> @work.WorkDescription</td>

										<td>@work.Mission.TeamMember.UserName</td>

										<td>@work.Status.Name</td>
										<td>
											<ul>
												@foreach (var attach in work.Attachments)
												{
													<li><a href="/Attachment/OpenFile?attachmentID=@attach.AttachmentID" target="_blank">@attach.FileName</a></li>
												}
											</ul>
										</td>
										<td>@work.TeamLeaderNote</td>
										@if (work.StatusID == 4)
										{
											<td>
												<a class="btn btn-success" id="approveBtn" href="/Work/LeaderApprove?workID=@work.WorkID">Approve</a>
												<hr>
												<a class="btn btn-danger text-white" id="denyBtn"  onclick="denyBtn()">Deny</a>
												<h5 id="Title" style="display:none">Reject note</h5>
												<textarea placeholder="Insert your notes" cols="40" rows="10" name="text" id="text_id"  style="resize:vertical;display:none"></textarea>
												<br>
												<a class="btn btn-info text-white " id="submit" onclick="submit()" style="display:none">Submit</a> <a class="btn btn-secondary  text-white" onclick="back()" id="back" style="display:none">Back</a>
												<script>
													 function denyBtn() {
															$("#approveBtn").toggle();
															$("#denyBtn").toggle();
															$("#text_id").toggle();
															$("#Title").toggle();
															$("#submit").toggle();
															$("#back").toggle();
														}
													function back() {
															$("#approveBtn").toggle();
															$("#denyBtn").toggle();
															$("#text_id").toggle();
															$("#Title").toggle();
															$("#submit").toggle();
															$("#back").toggle();
														}
													function submit() {
															var result = confirm("Are you sure?")
															if (result == true) {
																var text = $("#text_id").val();
																window.location.href = '@Url.Action("AddRejectNote", "Work")' + '?note=' + text + '&workID=' + @work.WorkID;
															}
														}
													
												</script>
											</td>
										}

										else
										{
											<td>
												<a class="btn bg-success disabled">Approve</a>
												<hr>
												<a class="btn bg-danger  disabled">Deny</a>
											</td>
										}

									</tr>
								}
							}
						</tbody>
					</table>

				</div>
			</div>
		</div>
		<div class="row mx-3">
			<a class="btn btn-info" href="/Mission/AllMissionsLeader?sprintID=@ViewBag.Mission.SprintID">Back</a>
		</div>
	</div>
</div>
@*</div>
*@

ProjectTrackerApplicationLayer/Views/Work/AllWorksManager.cshtml
@using ProjectTrackerBusinessLayer.Entities;
@using System.Linq;
@using System.Collections.Generic;
@model List<Work>;
@*@{
    Layout = "~/Views/Shared/_LayoutFluidContainer.cshtml";
}*@

<h1 class="text-center">Mission: @ViewBag.Mission.Name <br /> Works</h1>

<br />
<hr />


<div class="row justify-content-center">
    <div class=" col-12">
        <div class="card mx-3 shadow mb-4">

            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover cell-border" id="WorkTable" width="100%" cellspacing="0">
                        <thead>
                            <tr class="font-weight-bolder">
                                <th>
                                    Work Title
                                </th>
                                <th>
                                    Work Description
                                </th>
                                <th>
                                    Team Member
                                </th>
                                <th>
                                    Status
                                </th>
                                <th>
                                    Attachment Submitted
                                </th>
                                <th>
                                    Team Leader Note
                                </th>
                               
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                foreach (var work in Model)
                                {
                                    <tr>
                                        <td> @work.Name</td>
                                        <td> @work.WorkDescription</td>

                                        <td>@work.Mission.TeamMember.UserName</td>

                                        <td>@work.Status.Name</td>
                                        <td>
                                            <ul>
                                                @foreach (var attach in work.Attachments)
                                                {
                                                    <li><a href="/Attachment/OpenFile?attachmentID=@attach.AttachmentID" target="_blank">@attach.FileName</a></li>
                                                }
                                            </ul>
                                        </td>
                                        <td>@work.TeamLeaderNote</td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="row mx-3">
            <a class="btn btn-info" href="/Mission/AllMissionsManager?sprintID=@ViewBag.Mission.SprintID">Back</a>
		</div>
    </div>
</div>
@*</div>
*@

ProjectTrackerApplicationLayer/Views/Work/EditWork.cshtml
@using ProjectTrackerBusinessLayer.Entities;

@model Work
@{
    Layout = "~/Views/Shared/_FileInputLayout.cshtml";
    ViewData["Title"] = "Edit Work";
}

<br />
<h2 class="text-center">Edit Work Form</h2>
<br />
<hr />
<h4 class="text-center">@Model.Mission.Name</h4>
<script>
	function StatusChecker(event) 
    {
		event.preventDefault();
		var status = $('#Status').val();
		if (status == 4 || status == 5) {
			$('#statusModal').modal('show');
		}
		else {
            $("#workEditForm").submit();
		}
	}

	function dismissDialog() 
    {
		$('#statusModal').modal('hide');
	}

	function submitForm() 
    {
        $("#workEditForm").submit();
	}
</script>

<div class="modal fade" id="statusModal" tabindex="-1" role="dialog" aria-labelledby="statusCheckerModal"
	 aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="statusCheckerModal">Are you sure you want to change the status to Cancelled/Completed?</h5>
				<button class="close" type="button" data-dismiss="modal" aria-label="Close" onclick="dismissDialog()">
					<span aria-hidden="true">×</span>
				</button>
			</div>
			<div class="modal-body">Changing status to Cancelled/Compeleted will prevent you from making any changes, click cancel to go back and change the status and submit to proceed</div>
			<div class="modal-footer">
				<button class="btn btn-secondary" type="button" data-dismiss="modal" onclick="dismissDialog()">Cancel</button>
				<button class="btn btn-info" onclick="submitForm()">Submit</button>
			</div>
		</div>
	</div>
</div>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-8">
            <form id="workEditForm" asp-action="EdittingWork" method="post" enctype="multipart/form-data">
                <div asp-validation-summary="All" class="text-danger"></div>
                <input value="@ViewBag.mission.MissionID" name="MissionID" hidden />
                <input value="@ViewBag.mission.TeamMemberID" name="memberID" hidden />
                <input asp-for="WorkID" hidden />
                <div class="form-group">
                    <label asp-for="Name" class="label-control"></label>
                    <input asp-for="Name" class="form-control col-md-5" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group">
                    <label asp-for="WorkDescription" class="label-control"></label>
                    <textarea asp-for="WorkDescription" class="form-control"></textarea>
                    <span asp-validation-for="WorkDescription" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group">
                    <label class="label-control">Status</label>
                    <select id="Status" class="form-control" asp-for="StatusID">
                        @foreach (var status in (List<Status>)ViewBag.Statuses)
                        {
                            if (Model.StatusID == status.StatusID)
                            {
                                <option selected value="@status.StatusID">@status.Name</option>
                            }
                            else
                            {
                                <option value="@status.StatusID">@status.Name</option>
                            }
                        }
                    </select>
                </div>
                <br />
                <div class="form-group">
                    <label class="label-control">Attached files:</label>
                    <select class="form-control" id="filesMultiple" multiple name="AttachmentIDs">
                        @foreach (var attachment in (List<Attachment>)ViewBag.Attachments)
                        {

                            <option selected value="@attachment.AttachmentID">@attachment.FileName</option>

                        }
                    </select>
                    <input type="file" class="file" multiple value="@ViewBag.Attachments" id="FileLib" name="files"> </input>
                    <script>

                        // with plugin options
                        $("#FileLib").fileinput({ 'showUpload': false,   'previewFileType': 'any' });
                    </script>
                </div>
                <br />
                <button type="submit" value="Update" class="btn btn-outline-info" onclick="StatusChecker(event)">Update</button>
            </form>
        </div>
    </div>
</div>

ProjectTrackerApplicationLayer/Views/Work/MembersWorks.cshtml
@using ProjectTrackerBusinessLayer.Entities;
@using System.Linq;
@using System.Collections.Generic;
@model List<Work>;
@*@{
    Layout = "~/Views/Shared/_LayoutFluidContainer.cshtml";
}*@

<h1 class="text-center">Mission: @ViewBag.Mission.Name <br /> My Works</h1>
<br />

<h5 class="text-danger mx-3">Last date to submit work:@ViewBag.Mission.Sprint.EndDate </h5>

<hr />

<div class="row mx-3">
	@{
		//var workThatisAprroved = @Model.Where(x => x.StatusID == 2).ToList().Count;
		//var totalWork = Model.Count();
		//var missionCompleted = Model.Where(x => x.Mission.StatusID == 4 || x.Mission.StatusID == 5).ToList();
		if (@ViewBag.StatusesChecker)
		{


						<a class="btn bg-gradient-info text-white" href="/Work/AddWork?MissionID=@ViewBag.missionID">Add work</a>


		}
		else
		{
						<a class="btn bg-info text-white disabled">Add work</a>
		}

	}
</div>
<br />
<div class="row justify-content-center">
	<div class=" col-12">
		<div class="card mx-3 shadow mb-4">

			<div class="card-body">
				<div class="table-responsive">
					<table class="table table-bordered table-hover cell-border" id="WorkTable" width="100%" cellspacing="0">
						<thead>
							<tr class="font-weight-bolder">
								<th>
									Work Title
								</th>
								<th>
									Work Description
								</th>
								<th>
									Status
								</th>
								<th>
									Attachment Submitted
								</th>
								<th>
									Team Leader Note
								</th>
								<th>
									Action
								</th>
							</tr>
						</thead>
						<tbody>
							@{
								foreach (var work in Model)
								{
												<tr>
													<td> @work.Name</td>
													<td> @work.WorkDescription</td>
													<td>@work.Status.Name</td>
													<td>
														<ul>
															@foreach (var attach in work.Attachments)
												{
																<li><a href="/Attachment/OpenFile?attachmentID=@attach.AttachmentID" target="_blank"> @attach.FileName</a></li>
												}
														</ul>
													</td>
													<td>@work.TeamLeaderNote</td>
													@if (work.StatusID != 4 && work.StatusID != 5 && work.StatusID != 2 && ViewBag.StatusesChecker)
										{
														<td><a class="btn btn-outline-info" href="/Work/EditWork?workID=@work.WorkID&missionID=@work.MissionID">Edit</a></td>
										}
										else
										{
														<td><a data-toggle="tooltip" title="Can't edit check mission/work status" class="btn btn-outline-info disabled">Edit</a></td>
										}
												</tr>
								}
							}
						</tbody>
					</table>
				</div>
			</div>
		</div>
		<div class="row mx-3">
			<a class="btn btn-info" href="/Mission/MembersMissions?sprintID=@ViewBag.Mission.SprintID">Back</a>
		</div>
	</div>

</div>
@*</div>
*@
<script>
	$(document).ready(function () {
		$('[data-toggle="tooltip"]').tooltip();
	});
</script>